<?php

return [
    'ssh_timeout' => (int) env('SERVERPANEL_SSH_TIMEOUT', 20),
    'command_timeout' => (int) env('SERVERPANEL_COMMAND_TIMEOUT', 300),
    'allow_root_setup_mode' => (bool) env('SERVERPANEL_ALLOW_ROOT_SETUP_MODE', true),
    'auto_run_safe_commands' => (bool) env('SERVERPANEL_AUTO_RUN_SAFE_COMMANDS', true),
    'auto_run_safe_fixes' => (bool) env('SERVERPANEL_AUTO_RUN_SAFE_FIXES', false),
    'max_output_length' => (int) env('SERVERPANEL_MAX_OUTPUT_LENGTH', 120000),
    'report_base_path' => env('SERVERPANEL_REPORT_BASE_PATH', 'serverpanel/reports'),
    'ai' => [
        'provider' => env('SERVERPANEL_AI_PROVIDER', 'heuristic'),
        'model' => env('SERVERPANEL_AI_MODEL', 'gpt-4.1-mini'),
        'temperature' => (float) env('SERVERPANEL_AI_TEMPERATURE', 0.2),
        'timeout' => (int) env('SERVERPANEL_AI_TIMEOUT', 45),
    ],
    'blocked_commands' => [
        'rm -rf /',
        'rm -rf /*',
        'mkfs',
        'dd if=',
        ':(){ :|:& };:',
        'chmod -R 777 /',
        'chown -R root /',
        'userdel',
        'passwd',
        'shutdown',
        'poweroff',
        'reboot',
        'iptables -F',
        'ufw disable',
        'truncate -s 0 /etc/passwd',
    ],
    'approval_required_patterns' => [
        'apt install',
        'apt upgrade',
        'apt remove',
        'systemctl restart',
        'systemctl stop',
        'service restart',
        'composer install',
        'composer update',
        'npm install',
        'npm run build',
        'php artisan migrate',
        'certbot',
        'crontab',
        'chmod',
        'chown',
        'rm ',
        'mv /etc',
        'mv /usr',
        'mv /var',
    ],
    'safe_patterns' => [
        'whoami',
        'pwd',
        'hostname',
        'hostnamectl',
        'uname -a',
        'lsb_release -a',
        'php -v',
        'php -m',
        'mysql --version',
        'mariadb --version',
        'composer --version',
        'node -v',
        'npm -v',
        'df -h',
        'free -m',
        'uptime',
        'systemctl status',
        'journalctl -u',
        'tail -n 100',
        'ls',
        'cat /var/log',
        'cat /etc/',
    ],
];
