<?php

return [
    'panel_domain' => env('PANEL_DOMAIN', ''),
    'panel_port' => (int) env('PANEL_PORT'),
    'mail' => [
        'dkim_selector' => env('SERVERPANEL_DKIM_SELECTOR', 'default'),
        'dkim_domain' => env('SERVERPANEL_DKIM_DOMAIN', ''),
        'dkim_public_key' => env('SERVERPANEL_DKIM_PUBLIC_KEY', ''),
    ],
    'panel_cookie_name' => env('SERVERPANEL_PANEL_COOKIE', 'panel_session_proof'),
    'panel_token_lifetime' => (int) env('SERVERPANEL_PANEL_TOKEN_LIFETIME', 120),
    'panel_inactivity_timeout' => (int) env('SERVERPANEL_PANEL_INACTIVITY_TIMEOUT', 30),
    'ssl_auto_renew_enabled' => (bool) env('SERVERPANEL_SSL_AUTO_RENEW_ENABLED', true),
    'ssl_auto_renew_days' => (int) env('SERVERPANEL_SSL_AUTO_RENEW_DAYS', 30),
    'ssl_auto_renew_cooldown_hours' => (int) env('SERVERPANEL_SSL_AUTO_RENEW_COOLDOWN_HOURS', 12),
    'compound_public_suffixes' => [
        'com.bd',
        'net.bd',
        'org.bd',
        'edu.bd',
        'gov.bd',
        'ac.bd',
        'com.au',
        'net.au',
        'org.au',
        'co.uk',
        'org.uk',
        'gov.uk',
        'ac.uk',
        'co.jp',
        'com.sg',
        'com.my',
        'co.nz',
    ],
    'ssh_timeout' => (int) env('SERVERPANEL_SSH_TIMEOUT', 20),
    'command_timeout' => (int) env('SERVERPANEL_COMMAND_TIMEOUT', 300),
    'allow_root_setup_mode' => (bool) env('SERVERPANEL_ALLOW_ROOT_SETUP_MODE', true),
    'auto_run_safe_commands' => (bool) env('SERVERPANEL_AUTO_RUN_SAFE_COMMANDS', true),
    'auto_run_safe_fixes' => (bool) env('SERVERPANEL_AUTO_RUN_SAFE_FIXES', false),
    'max_output_length' => (int) env('SERVERPANEL_MAX_OUTPUT_LENGTH', 120000),
    'report_base_path' => env('SERVERPANEL_REPORT_BASE_PATH', 'serverpanel/reports'),
    'template_repository_dir' => env('SERVERPANEL_TEMPLATE_REPOSITORY_DIR', ''),
    'execution_api_base_url' => rtrim((string) env('SERVERPANEL_EXECUTION_API_BASE_URL', env('SERVERPANEL_API_BASE_URL', 'http://127.0.0.1:9500')), '/'),
    'execution_api_url' => env('SERVERPANEL_EXECUTION_API_URL', rtrim((string) env('SERVERPANEL_EXECUTION_API_BASE_URL', env('SERVERPANEL_API_BASE_URL', 'http://127.0.0.1:9500')), '/').'/api/v1/script/run'),
    'database_api_url' => env('SERVERPANEL_DATABASE_API_URL', rtrim((string) env('SERVERPANEL_EXECUTION_API_BASE_URL', env('SERVERPANEL_API_BASE_URL', 'http://127.0.0.1:9500')), '/').'/api/v1/database-request'),
    'database_api_token' => env('SERVERPANEL_DATABASE_API_TOKEN', env('SERVERPANEL_EXECUTION_API_TOKEN', '')),
    'filemanager_api_url' => env('SERVERPANEL_FILEMANAGER_API_URL', rtrim((string) env('SERVERPANEL_EXECUTION_API_BASE_URL', env('SERVERPANEL_API_BASE_URL', 'http://127.0.0.1:9500')), '/').'/api/v1/filemanager'),
    'execution_api_token' => env('SERVERPANEL_EXECUTION_API_TOKEN', ''),
    'execution_api_timeout' => (int) env('SERVERPANEL_EXECUTION_API_TIMEOUT', 60),
    'execution_api_upload_timeout' => (int) env('SERVERPANEL_EXECUTION_API_UPLOAD_TIMEOUT', 3600),
    'php_versions' => [
        '7.4',
        '8.0',
        '8.1',
        '8.2',
        '8.3',
        '8.4',
        '8.5',
    ],
    'website_php_defaults' => [
        'starter' => env('SERVERPANEL_WEBSITE_PHP_DEFAULT_STARTER', '8.3'),
        'wordpress' => env('SERVERPANEL_WEBSITE_PHP_DEFAULT_WORDPRESS', '8.3'),
    ],
    'installer_search_paths' => array_values(array_filter(array_map('trim', explode(',', env('SERVERPANEL_INSTALLER_SEARCH_PATHS', implode(',', [
        '/var/www/dscript',
    ])))))),
    'ai' => [
        'provider' => env('SERVERPANEL_AI_PROVIDER', 'heuristic'),
        'model' => env('SERVERPANEL_AI_MODEL', 'gpt-4.1-mini'),
        'temperature' => (float) env('SERVERPANEL_AI_TEMPERATURE', 0.2),
        'timeout' => (int) env('SERVERPANEL_AI_TIMEOUT', 45),
    ],
    'blocked_commands' => [
        'rm -rf /',
        'rm -rf /*',
        'mkfs',
        'dd if=',
        ':(){ :|:& };:',
        'chmod -R 777 /',
        'chown -R root /',
        'userdel',
        'passwd',
        'shutdown',
        'poweroff',
        'reboot',
        'iptables -F',
        'ufw disable',
        'truncate -s 0 /etc/passwd',
    ],
    'approval_required_patterns' => [
        'apt install',
        'apt upgrade',
        'apt remove',
        'systemctl restart',
        'systemctl stop',
        'service restart',
        'composer install',
        'composer update',
        'npm install',
        'npm run build',
        'php artisan migrate',
        'certbot',
        'crontab',
        'chmod',
        'chown',
        'rm ',
        'mv /etc',
        'mv /usr',
        'mv /var',
    ],
    'safe_patterns' => [
        'whoami',
        'pwd',
        'hostname',
        'hostnamectl',
        'uname -a',
        'lsb_release -a',
        'php -v',
        'php -m',
        'mysql --version',
        'mariadb --version',
        'composer --version',
        'node -v',
        'npm -v',
        'df -h',
        'free -m',
        'uptime',
        'systemctl status',
        'journalctl -u',
        'tail -n 100',
        'ls',
        'cat /var/log',
        'cat /etc/',
    ],
];
