#!/usr/bin/env bash
set -euo pipefail

root_path="${1:-}"
domain="${2:-}"
php_version="${3:-auto}"
start_directory="${4:-}"

if [[ -z "$root_path" || -z "$domain" ]]; then
  echo "Usage: create-demo-site.sh <root-path> <domain> [php-version]" >&2
  exit 1
fi

root_path="${root_path//\\//}"
root_path="${root_path%/}"
domain="${domain,,}"
php_version="${php_version:-auto}"
start_directory="${start_directory,,}"
start_directory="${start_directory//\\//}"
start_directory="${start_directory#/}"
start_directory="${start_directory%/}"
if [[ -z "$start_directory" ]]; then
  target_path="$root_path"
else
  start_directory="${start_directory//[^a-z0-9._-]/_}"
  start_directory="${start_directory//__/_}"
  if [[ "$start_directory" == "." || "$start_directory" == ".." ]]; then
    start_directory=""
  fi

  if [[ -z "$start_directory" ]]; then
    target_path="$root_path"
  else
    target_path="$root_path/$start_directory"
  fi
fi

mkdir -p "$target_path/extra"

cat > "$target_path/index.html" <<HTML
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>${domain} | Ready</title>
    <style>
        body{margin:0;min-height:100vh;display:grid;place-items:center;font-family:"Segoe UI",Tahoma,Geneva,Verdana,sans-serif;background:#0f172a;color:#0f172a;padding:24px}
        .card{width:min(720px,100%);background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 18px 40px rgba(2,6,23,.32)}
        .head{padding:24px;background:linear-gradient(135deg,#0ea5e9,#2563eb);color:#fff}
        .head h1{margin:0;font-size:26px}
        .body{padding:22px}
        .meta{display:grid;grid-template-columns:1fr 1fr;gap:12px}
        .item{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px}
        .label{font-size:11px;text-transform:uppercase;color:#64748b;font-weight:700;letter-spacing:.08em}
        .value{margin-top:6px;font-size:16px;font-weight:700}
    </style>
</head>
<body>
    <article class="card">
        <header class="head"><h1>${domain}</h1><p>Starter page generated by ServerPanel</p></header>
        <section class="body">
            <div class="meta">
                <div class="item"><div class="label">Configured PHP</div><div class="value">${php_version}</div></div>
                <div class="item"><div class="label">Status</div><div class="value">Ready</div></div>
            </div>
        </section>
    </article>
</body>
</html>
HTML

cat > "$target_path/extra/first-site-note.txt" <<TXT
This folder was created on first website creation.
Domain: ${domain}
Configured PHP: ${php_version}
Start Directory: ${start_directory}
Created at: $(date '+%Y-%m-%d %H:%M:%S')
TXT

exit 0
