[program:dpanel-queue]
command=/usr/bin/php __DPANEL_APP_DIR__/artisan queue:work --queue=server-commands,default --sleep=1 --tries=3 --timeout=300 --max-time=3600
directory=__DPANEL_APP_DIR__
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=360
redirect_stderr=true
stdout_logfile=__DPANEL_APP_DIR__/storage/logs/queue.log

[program:dpanel-heavy-queue]
command=/usr/bin/php __DPANEL_APP_DIR__/artisan queue:work --queue=heavy --sleep=1 --tries=1 --timeout=3600 --max-time=3600
directory=__DPANEL_APP_DIR__
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3700
redirect_stderr=true
stdout_logfile=__DPANEL_APP_DIR__/storage/logs/heavy-queue.log
