[program:dpanel-queue]
command=/usr/bin/php /var/www/dpanel/artisan queue:work redis --queue=default --sleep=1 --tries=3 --timeout=300 --max-time=3600
directory=/var/www/dpanel
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=360
redirect_stderr=true
stdout_logfile=/var/www/dpanel/storage/logs/queue.log

[program:dpanel-heavy-queue]
command=/usr/bin/php /var/www/dpanel/artisan queue:work redis --queue=heavy --sleep=1 --tries=1 --timeout=3600 --max-time=3600
directory=/var/www/dpanel
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3700
redirect_stderr=true
stdout_logfile=/var/www/dpanel/storage/logs/heavy-queue.log
