use std::{fs, path::Path, path::PathBuf};

use crate::app::{
    conf_basename, ensure_root, info, normalize_php_version, panel_aliases_for, run_status,
    write_string,
};

use super::{common::remove_duplicate_domain_vhosts, options::Sync};

pub(super) fn run(options: Sync) -> Result<(), String> {
    ensure_root()?;
    let app_root = PathBuf::from(&options.root_path);
    if !app_root.exists() {
        return Err(format!("Path does not exist: {}", app_root.display()));
    }

    let aliases = panel_aliases_for(&options.domain, &options.aliases, options.no_www);
    let conf_name = format!("{}.conf", conf_basename(&options.domain));
    let apache_path = Path::new("/etc/apache2/sites-available").join(&conf_name);
    let nginx_path = Path::new("/etc/nginx/sites-available").join(&conf_name);
    let nginx_enabled = Path::new("/etc/nginx/sites-enabled").join(&conf_name);
    for directory in [
        "/etc/apache2/sites-available",
        "/etc/nginx/sites-available",
        "/etc/nginx/sites-enabled",
    ] {
        fs::create_dir_all(directory)
            .map_err(|error| format!("failed to create {directory}: {error}"))?;
    }

    remove_duplicate_domain_vhosts(
        "/etc/apache2/sites-available",
        &options.domain,
        &apache_path,
    );
    remove_duplicate_domain_vhosts("/etc/apache2/sites-enabled", &options.domain, &apache_path);
    remove_duplicate_domain_vhosts("/etc/nginx/sites-available", &options.domain, &nginx_path);
    remove_duplicate_domain_vhosts("/etc/nginx/sites-enabled", &options.domain, &nginx_enabled);

    let php_version = normalize_php_version(&options.php_version, "8.3");
    let fpm_socket = super::site_pool::resolve_socket(&app_root, &php_version);
    let alias_line = if aliases.trim().is_empty() {
        String::new()
    } else {
        format!("\n    ServerAlias {}", aliases.trim())
    };
    let apache = format!(
        "\
<VirtualHost *:{apache_port}>
    ServerName {domain}{alias_line}
    DocumentRoot {root}

    <Directory {root}>
        AllowOverride All
        Require all granted
        Options FollowSymlinks
        FallbackResource /index.php
    </Directory>

    DirectoryIndex index.php index.html index.htm

    <IfModule mod_setenvif.c>
        SetEnvIf X-Forwarded-Proto \"^https$\" HTTPS=on
    </IfModule>

    <FilesMatch \\.php$>
        SetHandler \"proxy:unix:{fpm_socket}|fcgi://localhost/\"
    </FilesMatch>
</VirtualHost>
",
        apache_port = options.apache_backend_port,
        domain = options.domain,
        alias_line = alias_line,
        root = app_root.display(),
        fpm_socket = fpm_socket.display()
    );
    write_string(&apache_path, &apache)?;

    let certificate = format!("/etc/letsencrypt/live/{}/fullchain.pem", options.domain);
    let private_key = format!("/etc/letsencrypt/live/{}/privkey.pem", options.domain);
    let has_tls = Path::new(&certificate).is_file() && Path::new(&private_key).is_file();
    let proxy_block = format!(
        "\
        set $serverpanel_forwarded_proto $scheme;
        if ($http_x_forwarded_proto != \"\") {{
            set $serverpanel_forwarded_proto $http_x_forwarded_proto;
        }}
        proxy_pass http://127.0.0.1:{apache_port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $serverpanel_forwarded_proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;",
        apache_port = options.apache_backend_port
    );
    // Static files are served by nginx instead of travelling through Apache and
    // PHP-FPM. try_files covers a missing file and error_page covers a file nginx
    // may not read, so a wrong owner degrades to the backend instead of a 403.
    let site_body = format!(
        "\
    root {root};

    location ^~ /.well-known/ {{
{proxy_block}
    }}

    location ~ /\\. {{
        deny all;
    }}

    location ~* \\.(?:css|js|mjs|map|jpg|jpeg|gif|png|webp|avif|svg|ico|ttf|otf|woff|woff2|eot|mp4|webm|ogg|mp3|wav|pdf|webmanifest)$ {{
        try_files $uri @backend;
        error_page 403 = @backend;
        expires 30d;
        access_log off;
        add_header Cache-Control \"public, max-age=2592000\";
    }}

    location / {{
{proxy_block}
    }}

    location @backend {{
{proxy_block}
    }}",
        root = app_root.display(),
        proxy_block = proxy_block
    );
    // Without TLS everything is served over plain HTTP. With TLS the HTTP block only
    // keeps the ACME challenge path reachable and redirects the rest, so browsers never
    // mix an https page with http assets generated by the backend.
    let nginx = if has_tls {
        format!(
            "\
server {{
    listen {nginx_port};
    listen [::]:{nginx_port};
    server_name {domain} {aliases};

    location ^~ /.well-known/acme-challenge/ {{
{proxy_block}
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate {certificate};
    ssl_certificate_key {private_key};
    server_name {domain} {aliases};
    client_max_body_size {body_size};

{site_body}
}}
",
            nginx_port = options.nginx_primary_port,
            certificate = certificate,
            private_key = private_key,
            domain = options.domain,
            aliases = aliases,
            proxy_block = proxy_block,
            site_body = site_body,
            body_size = options.client_max_body_size
        )
    } else {
        format!(
            "\
server {{
    listen {nginx_port};
    listen [::]:{nginx_port};
    server_name {domain} {aliases};
    client_max_body_size {body_size};

{site_body}
}}
",
            nginx_port = options.nginx_primary_port,
            domain = options.domain,
            aliases = aliases,
            site_body = site_body,
            body_size = options.client_max_body_size
        )
    };
    write_string(&nginx_path, &nginx)?;
    let _ = fs::remove_file(&nginx_enabled);
    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;
        let _ = symlink(&nginx_path, &nginx_enabled);
    }

    let _ = run_status("a2ensite", &[&conf_name]);
    run_status("nginx", &["-t"])?;
    run_status("apache2ctl", &["-t"])?;
    run_status("systemctl", &["reload", "apache2"])?;
    run_status("systemctl", &["reload", "nginx"])?;
    info(&format!(
        "Vhost synchronized for {} -> {}",
        options.domain,
        app_root.display()
    ));
    let _ = options.panel_port;
    let _ = options.phpmyadmin_port;
    let _ = options.old_domain;
    Ok(())
}
