<?php

namespace App\Services\Website;

use App\Models\Website;
use App\Services\Filemanager\FilemanagerService;

class WebsiteService
{
    public function __construct(protected FilemanagerService $filemanagerService)
    {
    }

    public static function existWebsite(string $name)
    {
        $website = Website::where('domain', $name)->exists();
        if ($website) {
            return true;
        }

        return false;
    }

    /**
     * Create or refresh a lightweight demo site page inside the website root.
     *
     * @return array{index_html:?string, extra_note:?string}
     */
    public function createDemoSitePage(string $rootPath, string $domain, ?string $phpVersion = null, ?string $startDirectory = null, ?string $siteOwner = null): array
    {
        $rootPath = $this->normalizeAbsolutePath($rootPath);
        if ($rootPath === '') {
            throw new \InvalidArgumentException('Website root path is required.');
        }

        $normalizedDomain = $this->normalizeDomain($domain);
        $selectedPhpVersion = trim((string) $phpVersion);
        if ($selectedPhpVersion === '' || preg_match('/^\d+\.\d+$/', $selectedPhpVersion) !== 1) {
            $selectedPhpVersion = 'auto';
        }
        $normalizedStartDirectory = $this->normalizeRelativeDirectory((string) $startDirectory, '');
        $siteOwner = trim((string) $siteOwner);
        if ($siteOwner === '') {
            $siteOwner = basename(dirname($rootPath));
        }

        $targetPath = $this->joinPaths($rootPath, $normalizedStartDirectory);
        $safeDomain = htmlspecialchars($normalizedDomain, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $safePhpVersion = htmlspecialchars($selectedPhpVersion, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        $indexHtml = <<<HTML
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{$safeDomain} | Ready</title></head>
<body><main><h1>{$safeDomain}</h1><p>Starter page generated by ServerPanel.</p><p>Configured PHP: {$safePhpVersion}</p><p>Status: Ready</p></main></body>
</html>
HTML;
        $note = "This folder was created on first website creation.\n"
            ."Domain: {$normalizedDomain}\n"
            ."Configured PHP: {$selectedPhpVersion}\n"
            ."Start Directory: {$normalizedStartDirectory}\n"
            .'Created at: '.now()->toDateTimeString()."\n";

        $this->filemanagerService->writeTextFile($siteOwner, $targetPath.'/index.html', $indexHtml);
        $this->filemanagerService->writeTextFile($siteOwner, $targetPath.'/extra/first-site-note.txt', $note);

        return [
            'index_html' => $this->joinPaths($rootPath, $normalizedStartDirectory).'/index.html',
            'extra_note' => $this->joinPaths($rootPath, $normalizedStartDirectory).'/extra/first-site-note.txt',
        ];
    }

    public function normalizeAbsolutePath(string $path): string
    {
        return trim(str_replace('\\', '/', $path));
    }

    public function normalizeDomain(string $domain): string
    {
        return strtolower(trim($domain));
    }

    public function normalizeRelativeDirectory(string $path, string $fallback): string
    {
        $path = strtolower(trim(str_replace('\\', '/', $path)));
        $path = trim($path, '/');
        $path = (string) preg_replace('/[^a-z0-9._-]+/', '_', $path);
        $path = trim($path, '._-');

        if ($path === '' || $path === '.' || $path === '..') {
            return $fallback;
        }

        return substr($path, 0, 64);
    }

    public function joinPaths(string ...$segments): string
    {
        if ($segments === []) {
            return '';
        }

        $isAbsolute = str_starts_with(str_replace('\\', '/', $segments[0]), '/');
        $segments = array_values(array_filter(array_map(
            fn (string $segment): string => trim(str_replace('\\', '/', $segment), '/'),
            $segments,
        ), static fn (string $segment): bool => $segment !== ''));

        if ($segments === []) {
            return '';
        }

        return ($isAbsolute ? '/' : '').implode('/', $segments);
    }

    public function resolvePreviewRootPath(Website $website): string
    {
        $rootPath = $this->normalizeAbsolutePath((string) ($website->root_path ?? ''));
        if ($rootPath === '') {
            return '';
        }

        $startDirectory = $this->normalizeRelativeDirectory((string) ($website->start_directory ?? ''), '');
        if ($startDirectory === '') {
            return $rootPath;
        }

        return $this->joinPaths($rootPath, $startDirectory);
    }

    public function resolveWebsiteDocumentRoot(string $rootPath, ?string $startDirectory = null): string
    {
        $normalizedRootPath = $this->normalizeAbsolutePath($rootPath);
        if ($normalizedRootPath === '') {
            return '';
        }

        $normalizedStartDirectory = $this->normalizeRelativeDirectory((string) $startDirectory, '');
        if ($normalizedStartDirectory === '') {
            return $normalizedRootPath;
        }

        return $this->joinPaths($normalizedRootPath, $normalizedStartDirectory);
    }

    public function resolvePreviewFile(string $path): string|false
    {
        $normalized = $this->normalizeAbsolutePath($path);
        if ($normalized === '') {
            return false;
        }

        $real = realpath($normalized);
        if ($real !== false && is_file($real)) {
            return $real;
        }

        if (is_dir($normalized)) {
            foreach (['index.html', 'index.php'] as $fileName) {
                $candidate = realpath($normalized.DIRECTORY_SEPARATOR.$fileName);
                if ($candidate !== false && is_file($candidate)) {
                    return $candidate;
                }
            }
        }

        if (! is_dir($normalized)) {
            $directory = dirname($normalized);
            foreach (['index.html', 'index.php'] as $fileName) {
                $candidate = realpath($directory.DIRECTORY_SEPARATOR.$fileName);
                if ($candidate !== false && is_file($candidate)) {
                    return $candidate;
                }
            }
        }

        return false;
    }

    public function pathIsInside(string $file, string $directory): bool
    {
        $file = $this->normalizeAbsolutePath($file);
        $directory = rtrim($this->normalizeAbsolutePath($directory), '/');

        if ($file === '' || $directory === '') {
            return false;
        }

        return $file === $directory || str_starts_with($file, $directory.'/');
    }

}
