<?php

namespace App\Services\Website;

use App\Models\Website;
use App\Services\Filemanager\FilemanagerService;

class WebsiteService
{
    public function __construct(protected FilemanagerService $filemanagerService)
    {
    }

    public static function existWebsite(string $name)
    {
        $website = Website::where('domain', $name)->exists();
        if ($website) {
            return true;
        }

        return false;
    }

    /**
     * Create or refresh a lightweight demo site page inside the website root.
     *
     * @return array{index_php:string, index_html:null, extra_note:null}
     */
    public function createDemoSitePage(string $rootPath, string $domain, ?string $phpVersion = null, ?string $startDirectory = null, ?string $siteOwner = null): array
    {
        $rootPath = $this->normalizeAbsolutePath($rootPath);
        if ($rootPath === '') {
            throw new \InvalidArgumentException('Website root path is required.');
        }

        $normalizedDomain = $this->normalizeDomain($domain);
        $selectedPhpVersion = trim((string) $phpVersion);
        if ($selectedPhpVersion === '' || preg_match('/^\d+\.\d+$/', $selectedPhpVersion) !== 1) {
            $selectedPhpVersion = 'auto';
        }
        $normalizedStartDirectory = $this->normalizeRelativeDirectory((string) $startDirectory, '');
        $siteOwner = trim((string) $siteOwner);
        if ($siteOwner === '') {
            $siteOwner = basename(dirname($rootPath));
        }

        $targetPath = $this->joinPaths($rootPath, $normalizedStartDirectory);
        $template = @file_get_contents(resource_path('stubs/website/index.php'));
        if (! is_string($template) || ! str_contains($template, '@serverpanel-starter')) {
            throw new \RuntimeException('Shared website starter template is unavailable.');
        }

        $indexPhp = $targetPath.'/index.php';
        $indexHtml = $targetPath.'/index.html';
        $this->filemanagerService->writeTextFile($siteOwner, $indexPhp, $template);
        if (is_file($indexHtml)) {
            $existingHtml = (string) @file_get_contents($indexHtml);
            if (str_contains($existingHtml, 'Starter page generated by ServerPanel')) {
                $this->filemanagerService->deletePath($siteOwner, $indexHtml);
            }
        }

        return [
            'index_php' => $indexPhp,
            'index_html' => null,
            'extra_note' => null,
        ];
    }

    public function normalizeAbsolutePath(string $path): string
    {
        return trim(str_replace('\\', '/', $path));
    }

    public function normalizeDomain(string $domain): string
    {
        return strtolower(trim($domain));
    }

    public function normalizeRelativeDirectory(string $path, string $fallback): string
    {
        $path = strtolower(trim(str_replace('\\', '/', $path)));
        $path = trim($path, '/');
        $path = (string) preg_replace('/[^a-z0-9._-]+/', '_', $path);
        $path = trim($path, '._-');

        if ($path === '' || $path === '.' || $path === '..') {
            return $fallback;
        }

        return substr($path, 0, 64);
    }

    public function joinPaths(string ...$segments): string
    {
        if ($segments === []) {
            return '';
        }

        $isAbsolute = str_starts_with(str_replace('\\', '/', $segments[0]), '/');
        $segments = array_values(array_filter(array_map(
            fn (string $segment): string => trim(str_replace('\\', '/', $segment), '/'),
            $segments,
        ), static fn (string $segment): bool => $segment !== ''));

        if ($segments === []) {
            return '';
        }

        return ($isAbsolute ? '/' : '').implode('/', $segments);
    }

    public function resolvePreviewRootPath(Website $website): string
    {
        $rootPath = $this->normalizeAbsolutePath((string) ($website->root_path ?? ''));
        if ($rootPath === '') {
            return '';
        }

        $startDirectory = $this->normalizeRelativeDirectory((string) ($website->start_directory ?? ''), '');
        if ($startDirectory === '') {
            return $rootPath;
        }

        return $this->joinPaths($rootPath, $startDirectory);
    }

    public function resolveWebsiteDocumentRoot(string $rootPath, ?string $startDirectory = null): string
    {
        $normalizedRootPath = $this->normalizeAbsolutePath($rootPath);
        if ($normalizedRootPath === '') {
            return '';
        }

        $normalizedStartDirectory = $this->normalizeRelativeDirectory((string) $startDirectory, '');
        if ($normalizedStartDirectory === '') {
            return $normalizedRootPath;
        }

        return $this->joinPaths($normalizedRootPath, $normalizedStartDirectory);
    }

    public function resolvePreviewFile(string $path): string|false
    {
        $normalized = $this->normalizeAbsolutePath($path);
        if ($normalized === '') {
            return false;
        }

        $real = realpath($normalized);
        if ($real !== false && is_file($real)) {
            return $real;
        }

        if (is_dir($normalized)) {
            foreach (['index.html', 'index.php'] as $fileName) {
                $candidate = realpath($normalized.DIRECTORY_SEPARATOR.$fileName);
                if ($candidate !== false && is_file($candidate)) {
                    return $candidate;
                }
            }
        }

        if (! is_dir($normalized)) {
            $directory = dirname($normalized);
            foreach (['index.html', 'index.php'] as $fileName) {
                $candidate = realpath($directory.DIRECTORY_SEPARATOR.$fileName);
                if ($candidate !== false && is_file($candidate)) {
                    return $candidate;
                }
            }
        }

        return false;
    }

    public function pathIsInside(string $file, string $directory): bool
    {
        $file = $this->normalizeAbsolutePath($file);
        $directory = rtrim($this->normalizeAbsolutePath($directory), '/');

        if ($file === '' || $directory === '') {
            return false;
        }

        return $file === $directory || str_starts_with($file, $directory.'/');
    }

}
