<script setup>
import LegalLayout from '@/Layouts/LegalLayout.vue';
import { Head, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';

defineProps({
    contactEmail: { type: String, default: '' },
});

const page = usePage();
const appName = computed(() => page.props.app?.name ?? 'dPanel');
</script>

<template>
    <Head title="Terms and Conditions" />

    <LegalLayout title="Terms &amp; Conditions" updated-at="August 27, 2026">
        <p>
            These Terms &amp; Conditions ("Terms") govern your access to and use of {{ appName }} (the "Panel"),
            including its server, website, mail, database, DNS, backup, AI Gateway, and AI Chat Engine features. By
            accessing or using the Panel, you agree to be bound by these Terms.
        </p>

        <section>
            <h2>1. Use of the Panel</h2>
            <ul>
                <li>You must be authorized by the Panel's administrator to hold an account, and are responsible for maintaining the confidentiality of your login credentials and any API keys or tokens you configure.</li>
                <li>You agree to use the Panel only for lawful purposes and in accordance with the acceptable-use policies of any third-party service you connect (AI providers, Telegram, Facebook, hosting/DNS providers, etc.).</li>
                <li>Access levels (admin, reseller, general user) are assigned by the administrator and determine which features and data you can view or modify.</li>
            </ul>
        </section>

        <section>
            <h2>2. Third-Party Services &amp; API Keys</h2>
            <p>
                Certain features require you to supply your own credentials for third-party services — for example,
                AI provider API keys (OpenAI, Anthropic, Google Gemini, etc.), Telegram bot tokens, or Facebook Page
                access tokens. You are solely responsible for:
            </p>
            <ul>
                <li>The validity, security, and lawful use of any credentials you provide.</li>
                <li>Any charges, rate limits, or usage incurred with the third-party provider as a result of requests made through the Panel.</li>
                <li>Complying with that provider's own terms of service and content policies.</li>
            </ul>
            <p>
                We are not responsible for the availability, accuracy, or content of responses generated by
                third-party AI providers, nor for the actions of third-party messaging platforms.
            </p>
        </section>

        <section>
            <h2>3. AI-Generated Content</h2>
            <p>
                The AI Gateway and AI Chat Engine features use third-party AI models to generate text and replies,
                including automated replies sent to your customers or contacts on connected channels (Telegram,
                Facebook Messenger, and Facebook comments). AI-generated content may be inaccurate, incomplete, or
                inappropriate in some cases. You are responsible for reviewing and moderating AI auto-reply behavior
                (including via the AI on/off toggle and system prompts) and for any consequences of messages sent
                automatically on your behalf.
            </p>
        </section>

        <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree not to use the Panel to:</p>
            <ul>
                <li>Send unsolicited bulk messages ("spam") through connected channels, or otherwise violate the messaging platform's policies (Telegram, Meta/Facebook, etc.).</li>
                <li>Attempt to gain unauthorized access to any system, account, or data, including through the Panel's webhooks or APIs.</li>
                <li>Upload, generate, or transmit content that is unlawful, infringing, or that violates the rights of others.</li>
                <li>Interfere with or disrupt the integrity or performance of the Panel or connected third-party services.</li>
            </ul>
        </section>

        <section>
            <h2>5. Service Availability</h2>
            <p>
                The Panel is provided on an "as is" and "as available" basis. We do not guarantee uninterrupted or
                error-free operation, including for scheduled/broadcast messages, webhook processing, or AI
                responses, which may depend on the availability of third-party services outside our control.
            </p>
        </section>

        <section>
            <h2>6. Data &amp; Backups</h2>
            <p>
                While the Panel provides backup and recovery tools, you remain responsible for maintaining your own
                copies of critical data. We are not liable for data loss resulting from misuse of the Panel,
                third-party service outages, or events outside our reasonable control.
            </p>
        </section>

        <section>
            <h2>7. Limitation of Liability</h2>
            <p>
                To the maximum extent permitted by law, {{ appName }} and its operators shall not be liable for any
                indirect, incidental, special, or consequential damages arising from your use of the Panel, including
                damages resulting from AI-generated content, third-party service failures, or actions taken through
                connected channels.
            </p>
        </section>

        <section>
            <h2>8. Termination</h2>
            <p>
                Access to the Panel may be suspended or terminated at any time, with or without notice, for conduct
                that violates these Terms, applicable law, or the policies of a connected third-party service.
            </p>
        </section>

        <section>
            <h2>9. Changes to These Terms</h2>
            <p>
                We may revise these Terms from time to time. Material changes will be reflected by updating the
                "Last updated" date above. Continued use of the Panel after changes take effect constitutes
                acceptance of the revised Terms.
            </p>
        </section>

        <section>
            <h2>10. Contact Us</h2>
            <p>
                Questions about these Terms can be directed to
                <a v-if="contactEmail" :href="`mailto:${contactEmail}`">{{ contactEmail }}</a><span v-else>the administrator of this panel</span>.
            </p>
        </section>

        <p class="text-xs text-slate-500">
            See also our <a href="/privacy-policy">Privacy Policy</a> for details on how information is collected and used.
        </p>
    </LegalLayout>
</template>
