<?php

namespace App\Http\Controllers;

use App\Models\Website;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Inertia\Inertia;
use Inertia\Response;

class ApacheController extends Controller
{
    public function index(): Response
    {
        $apache = $this->apacheRuntimeInfo();
        $nginx = $this->nginxRuntimeInfo();
        $websites = Website::query()
            ->orderBy('domain')
            ->get()
            ->map(function (Website $website): array {
                $domain = strtolower(trim((string) ($website->domain ?? '')));
                $root = trim((string) ($website->root_path ?? ''));
                if ($root === '') {
                    $root = $this->defaultRootPathForDomain($domain);
                }

                return [
                    'id' => (string) $website->id,
                    'domain' => $domain,
                    'root_path' => $root,
                    'status' => (string) ($website->status ?? 'unknown'),
                    'enable_ssl' => (bool) ($website->enable_ssl ?? false),
                ];
            })
            ->values()
            ->all();

        $sharedPath = $apache['shared_vhost_file'];
        $sharedExists = is_string($sharedPath) && $sharedPath !== '' && is_file($sharedPath);

        return Inertia::render('Apache/Index', [
            'apache' => [
                ...$apache,
                'service_status' => $this->detectServiceStatus($apache),
                'shared_vhost_exists' => $sharedExists,
                'shared_vhost_last_modified' => $sharedExists ? date('Y-m-d H:i:s', (int) @filemtime($sharedPath)) : null,
            ],
            'nginx' => [
                ...$nginx,
                'service_status' => $this->detectNginxServiceStatus($nginx),
            ],
            'websites' => $websites,
        ]);
    }

    public function runAction(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'action' => ['required', 'in:test,start,stop,restart,reload,status,renew_ssl'],
        ]);

        $apache = $this->apacheRuntimeInfo();
        [$command, $label] = $this->buildCommandForAction((string) $validated['action'], $apache);
        if ($command === '') {
            return redirect()->route('apache.index')->with('error', 'Action is not supported on this server.');
        }

        $result = Process::timeout(180)->run($command);
        $output = trim($result->output()."\n".$result->errorOutput());
        $message = $output !== '' ? $output : ($result->successful() ? 'Command completed.' : 'Command failed.');

        if (! $result->successful()) {
            return redirect()->route('apache.index')->with('error', $label.":\n".$message);
        }

        return redirect()->route('apache.index')->with('success', $label." completed.\n".$message);
    }

    public function syncSharedWebsites(): RedirectResponse
    {
        $apache = $this->apacheRuntimeInfo();
        $target = trim((string) ($apache['shared_vhost_file'] ?? ''));
        if ($target === '') {
            return redirect()->route('apache.index')->with('error', 'Shared vhost file path is not configured.');
        }

        $websites = Website::query()->orderBy('domain')->get();
        $entries = [];

        foreach ($websites as $website) {
            $domain = strtolower(trim((string) ($website->domain ?? '')));
            if ($domain === '') {
                continue;
            }

            $rootPath = trim((string) ($website->root_path ?? ''));
            if ($rootPath === '') {
                $rootPath = $this->defaultRootPathForDomain($domain);
            }

            $entries[] = $this->renderVhostBlock($domain, $rootPath);
        }

        $contents = implode("\n\n", [
            '# Auto-generated by ServerPanel Apache Manager',
            '# Changes may be overwritten by "Sync Shared Websites" action',
            ...$entries,
        ]);

        try {
            File::ensureDirectoryExists(dirname($target));
            File::put($target, $contents);
        } catch (\Throwable $e) {
            return redirect()->route('apache.index')->with('error', 'Cannot write Apache config file: '.$e->getMessage());
        }

        $testCommand = $this->buildCommandForAction('test', $apache)[0];
        if ($testCommand !== '') {
            $testResult = Process::timeout(120)->run($testCommand);
            if (! $testResult->successful()) {
                $testOutput = trim($testResult->output()."\n".$testResult->errorOutput());

                return redirect()
                    ->route('apache.index')
                    ->with('error', "Shared websites config generated, but Apache test failed:\n".$testOutput);
            }
        }

        return redirect()
            ->route('apache.index')
            ->with('success', 'Shared websites Apache config generated successfully.');
    }

    /**
     * @param array<string, mixed> $apache
     * @return array{0:string,1:string}
     */
    private function buildCommandForAction(string $action, array $apache): array
    {
        $os = (string) ($apache['os_family'] ?? '');

        if ($os === 'Windows') {
            $httpd = (string) ($apache['httpd_path'] ?? '');
            $serviceName = (string) ($apache['service_name'] ?? 'wampapache64');
            $mainConf = (string) ($apache['main_conf'] ?? '');

            if ($httpd === '' || ! is_file($httpd)) {
                return ['', 'Apache binary not found'];
            }

            return match ($action) {
                'test' => [$mainConf !== '' ? "\"{$httpd}\" -t -f \"{$mainConf}\"" : "\"{$httpd}\" -t", 'Apache config test'],
                'start' => ["\"{$httpd}\" -k start -n \"{$serviceName}\"", 'Apache start'],
                'stop' => ["\"{$httpd}\" -k stop -n \"{$serviceName}\"", 'Apache stop'],
                'restart' => ["\"{$httpd}\" -k restart -n \"{$serviceName}\"", 'Apache restart'],
                'reload' => ["\"{$httpd}\" -k restart -n \"{$serviceName}\"", 'Apache reload'],
                'status' => ["sc query \"{$serviceName}\"", 'Apache status'],
                'renew_ssl' => ['certbot renew', 'SSL renew'],
                default => ['', 'Unsupported action'],
            };
        }

        return match ($action) {
            'test' => ['apache2ctl -t', 'Apache config test'],
            'start' => ['systemctl start apache2', 'Apache start'],
            'stop' => ['systemctl stop apache2', 'Apache stop'],
            'restart' => ['systemctl restart apache2', 'Apache restart'],
            'reload' => ['apache2ctl -t && systemctl reload apache2', 'Apache reload'],
            'status' => ['systemctl status apache2 --no-pager', 'Apache status'],
            'renew_ssl' => ['certbot renew', 'SSL renew'],
            default => ['', 'Unsupported action'],
        };
    }

    /**
     * @param array<string, mixed> $apache
     */
    private function detectServiceStatus(array $apache): string
    {
        if ((string) ($apache['os_family'] ?? '') === 'Windows') {
            $serviceName = (string) ($apache['service_name'] ?? 'wampapache64');
            $result = Process::timeout(20)->run("sc query \"{$serviceName}\"");
            $output = strtoupper($result->output().' '.$result->errorOutput());
            if (str_contains($output, 'RUNNING')) {
                return 'running';
            }
            if (str_contains($output, 'STOPPED')) {
                return 'stopped';
            }

            return 'unknown';
        }

        $result = Process::timeout(20)->run('systemctl is-active apache2');
        $status = trim($result->output());

        return $status !== '' ? $status : 'unknown';
    }

    /**
     * @param array<string, mixed> $nginx
     */
    private function detectNginxServiceStatus(array $nginx): string
    {
        if ((string) ($nginx['os_family'] ?? '') === 'Windows') {
            $serviceName = (string) ($nginx['service_name'] ?? 'wampnginx64');
            $result = Process::timeout(20)->run("sc query \"{$serviceName}\"");
            $output = strtoupper($result->output().' '.$result->errorOutput());
            if (str_contains($output, 'RUNNING')) {
                return 'running';
            }
            if (str_contains($output, 'STOPPED')) {
                return 'stopped';
            }

            return 'unknown';
        }

        $result = Process::timeout(20)->run('systemctl is-active nginx');
        $status = trim($result->output());

        return $status !== '' ? $status : 'unknown';
    }

    /**
     * @return array<string, mixed>
     */
    private function apacheRuntimeInfo(): array
    {
        $os = strtoupper(PHP_OS_FAMILY);

        if ($os === 'WINDOWS') {
            $httpd = trim((string) env('APACHE_HTTPD_PATH', ''));
            if ($httpd === '') {
                $matches = glob('D:/wamp64/bin/apache/apache*/bin/httpd.exe');
                $httpd = is_array($matches) && count($matches) > 0 ? (string) end($matches) : '';
            }

            $mainConf = trim((string) env('APACHE_MAIN_CONF_PATH', ''));
            if ($mainConf === '' && $httpd !== '') {
                $mainConf = dirname(dirname($httpd)).DIRECTORY_SEPARATOR.'conf'.DIRECTORY_SEPARATOR.'httpd.conf';
            }

            $sharedVhost = trim((string) env('APACHE_SHARED_VHOST_FILE', ''));
            if ($sharedVhost === '' && $mainConf !== '') {
                $sharedVhost = dirname($mainConf).DIRECTORY_SEPARATOR.'extra'.DIRECTORY_SEPARATOR.'httpd-vhosts-serverpanel.conf';
            }

            return [
                'os_family' => 'Windows',
                'httpd_path' => $httpd,
                'service_name' => trim((string) env('APACHE_SERVICE_NAME', 'wampapache64')),
                'main_conf' => $mainConf,
                'shared_vhost_file' => $sharedVhost,
                'include_hint' => 'Include conf/extra/httpd-vhosts-serverpanel.conf in httpd.conf if not already included.',
            ];
        }

        return [
            'os_family' => 'Linux',
            'httpd_path' => '/usr/sbin/apache2',
            'service_name' => 'apache2',
            'main_conf' => '/etc/apache2/apache2.conf',
            'shared_vhost_file' => trim((string) env('APACHE_SHARED_VHOST_FILE', '/etc/apache2/sites-available/serverpanel-shared.conf')),
            'include_hint' => 'Enable site: ln -s sites-available/serverpanel-shared.conf sites-enabled/serverpanel-shared.conf and reload apache.',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function nginxRuntimeInfo(): array
    {
        $os = strtoupper(PHP_OS_FAMILY);

        if ($os === 'WINDOWS') {
            $binaryPath = trim((string) env('NGINX_BINARY_PATH', ''));
            if ($binaryPath === '') {
                $matches = glob('D:/wamp64/bin/nginx/nginx*/nginx.exe');
                $binaryPath = is_array($matches) && count($matches) > 0 ? (string) end($matches) : '';
            }

            $mainConf = trim((string) env('NGINX_MAIN_CONF_PATH', ''));
            if ($mainConf === '' && $binaryPath !== '') {
                $mainConf = dirname($binaryPath).DIRECTORY_SEPARATOR.'conf'.DIRECTORY_SEPARATOR.'nginx.conf';
            }

            return [
                'os_family' => 'Windows',
                'binary_path' => $binaryPath,
                'service_name' => trim((string) env('NGINX_SERVICE_NAME', 'wampnginx64')),
                'main_conf' => $mainConf,
                'sites_available_path' => '',
                'sites_enabled_path' => '',
                'include_hint' => 'Use include directives in nginx.conf/server blocks for generated site files.',
            ];
        }

        return [
            'os_family' => 'Linux',
            'binary_path' => '/usr/sbin/nginx',
            'service_name' => 'nginx',
            'main_conf' => '/etc/nginx/nginx.conf',
            'sites_available_path' => '/etc/nginx/sites-available',
            'sites_enabled_path' => '/etc/nginx/sites-enabled',
            'include_hint' => 'Enable Nginx sites by linking sites-available to sites-enabled, then run nginx -t and reload.',
        ];
    }

    private function defaultRootPathForDomain(string $domain): string
    {
        $base = trim((string) config('app.server_base_dir', ''));
        if ($base === '') {
            $base = strtoupper(PHP_OS_FAMILY) === 'WINDOWS' ? dirname(base_path()) : '/home';
        }

        $owner = preg_replace('/[^a-z0-9]+/i', '_', $domain) ?: 'website';
        $owner = trim((string) $owner, '_');
        if ($owner === '') {
            $owner = 'website';
        }

        return rtrim($base, "\\/").DIRECTORY_SEPARATOR.$owner.DIRECTORY_SEPARATOR.'public_html';
    }

    private function renderVhostBlock(string $domain, string $rootPath): string
    {
        $safeRoot = str_replace('\\', '/', trim($rootPath));
        $logDomain = preg_replace('/[^a-z0-9\.\-_]+/i', '-', $domain) ?: 'site';

        return <<<CONF
<VirtualHost *:80>
    ServerName {$domain}
    ServerAlias www.{$domain}
    DocumentRoot "{$safeRoot}"

    <Directory "{$safeRoot}">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog "\${APACHE_LOG_DIR}/{$logDomain}-error.log"
    CustomLog "\${APACHE_LOG_DIR}/{$logDomain}-access.log" combined
</VirtualHost>
CONF;
    }
}
