[program:panel-agent]
command=/usr/bin/python3 /usr/local/panel/agent/panel_agent.py
directory=/usr/local/panel/agent
autostart=true
autorestart=true
stderr_logfile=/opt/likesoft/logs/agent.err.log
stdout_logfile=/opt/likesoft/logs/agent.out.log
user=root
