<?php

namespace App\Http\Controllers;

use App\Models\Website;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;
use Inertia\Inertia;
use Inertia\Response;

class ApacheController extends Controller
{
    private const DEFAULT_APACHE_BACKEND_PORT = 8080;
    private const DEFAULT_NGINX_PRIMARY_PORT = 80;

    public function index(Request $request): Response
    {
        $apache = $this->apacheRuntimeInfo();
        $nginx = $this->nginxRuntimeInfo();
        $websites = Website::query()
            ->orderBy('domain')
            ->get()
            ->map(function (Website $website): array {
                $domain = strtolower(trim((string) ($website->domain ?? '')));
                $root = trim((string) ($website->root_path ?? ''));
                if ($root === '') {
                    $root = $this->defaultRootPathForDomain($domain);
                }

                return [
                    'id' => (string) $website->id,
                    'domain' => $domain,
                    'root_path' => $root,
                    'php_version' => trim((string) ($website->php_version ?? '8.3')),
                    'status' => (string) ($website->status ?? 'unknown'),
                    'enable_ssl' => (bool) ($website->enable_ssl ?? false),
                ];
            })
            ->values()
            ->all();
        $selectedWebsiteId = trim((string) $request->query('website_id', ''));
        $selectedWebsite = collect($websites)
            ->first(fn (array $item): bool => (string) ($item['id'] ?? '') === $selectedWebsiteId);

        if (! is_array($selectedWebsite)) {
            $selectedWebsite = $websites[0] ?? null;
        }

        $selectedWebsiteId = is_array($selectedWebsite)
            ? trim((string) ($selectedWebsite['id'] ?? ''))
            : '';

        $sharedPath = $apache['shared_vhost_file'];
        $sharedExists = is_string($sharedPath) && $sharedPath !== '' && is_file($sharedPath);

        return Inertia::render('Apache/Index', [
            'apache' => [
                ...$apache,
                'service_status' => $this->detectServiceStatus($apache),
                'shared_vhost_exists' => $sharedExists,
                'shared_vhost_last_modified' => $sharedExists ? date('Y-m-d H:i:s', (int) @filemtime($sharedPath)) : null,
            ],
            'nginx' => [
                ...$nginx,
                'service_status' => $this->detectNginxServiceStatus($nginx),
            ],
            'websites' => $websites,
            'selectedWebsiteId' => $selectedWebsiteId !== '' ? $selectedWebsiteId : null,
            'selectedWebsite' => $selectedWebsite,
            'vhostPreview' => $this->buildWebsiteVhostPreview($selectedWebsite, $apache, $nginx),
        ]);
    }

    public function runAction(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'action' => ['required', 'in:test,start,stop,restart,reload,status,renew_ssl'],
        ]);

        $apache = $this->apacheRuntimeInfo();
        [$command, $label] = $this->buildCommandForAction((string) $validated['action'], $apache);
        if ($command === '') {
            return redirect()->route('apache.index')->with('error', 'Action is not supported on this server.');
        }

        $result = Process::timeout(180)->run($command);
        $output = trim($result->output()."\n".$result->errorOutput());
        $message = $output !== '' ? $output : ($result->successful() ? 'Command completed.' : 'Command failed.');

        if (! $result->successful()) {
            return redirect()->route('apache.index')->with('error', $label.":\n".$message);
        }

        return redirect()->route('apache.index')->with('success', $label." completed.\n".$message);
    }

    public function syncSharedWebsites(): RedirectResponse
    {
        $apache = $this->apacheRuntimeInfo();
        $target = trim((string) ($apache['shared_vhost_file'] ?? ''));
        if ($target === '') {
            return redirect()->route('apache.index')->with('error', 'Shared vhost file path is not configured.');
        }

        $websites = Website::query()->orderBy('domain')->get();
        $entries = [];

        foreach ($websites as $website) {
            $domain = strtolower(trim((string) ($website->domain ?? '')));
            if ($domain === '') {
                continue;
            }

            $rootPath = trim((string) ($website->root_path ?? ''));
            if ($rootPath === '') {
                $rootPath = $this->defaultRootPathForDomain($domain);
            }

            $entries[] = $this->renderVhostBlock($domain, $rootPath);
        }

        $contents = implode("\n\n", [
            '# Auto-generated by ServerPanel Apache Manager',
            '# Changes may be overwritten by "Sync Shared Websites" action',
            ...$entries,
        ]);

        try {
            File::ensureDirectoryExists(dirname($target));
            File::put($target, $contents);
        } catch (\Throwable $e) {
            return redirect()->route('apache.index')->with('error', 'Cannot write Apache config file: '.$e->getMessage());
        }

        $testCommand = $this->buildCommandForAction('test', $apache)[0];
        if ($testCommand !== '') {
            $testResult = Process::timeout(120)->run($testCommand);
            if (! $testResult->successful()) {
                $testOutput = trim($testResult->output()."\n".$testResult->errorOutput());

                return redirect()
                    ->route('apache.index')
                    ->with('error', "Shared websites config generated, but Apache test failed:\n".$testOutput);
            }
        }

        return redirect()
            ->route('apache.index')
            ->with('success', 'Shared websites Apache config generated successfully.');
    }

    /**
     * @param array<string, mixed> $apache
     * @return array{0:string,1:string}
     */
    private function buildCommandForAction(string $action, array $apache): array
    {
        $os = (string) ($apache['os_family'] ?? '');

        if ($os === 'Windows') {
            $httpd = (string) ($apache['httpd_path'] ?? '');
            $serviceName = (string) ($apache['service_name'] ?? 'wampapache64');
            $mainConf = (string) ($apache['main_conf'] ?? '');

            if ($httpd === '' || ! is_file($httpd)) {
                return ['', 'Apache binary not found'];
            }

            return match ($action) {
                'test' => [$mainConf !== '' ? "\"{$httpd}\" -t -f \"{$mainConf}\"" : "\"{$httpd}\" -t", 'Apache config test'],
                'start' => ["\"{$httpd}\" -k start -n \"{$serviceName}\"", 'Apache start'],
                'stop' => ["\"{$httpd}\" -k stop -n \"{$serviceName}\"", 'Apache stop'],
                'restart' => ["\"{$httpd}\" -k restart -n \"{$serviceName}\"", 'Apache restart'],
                'reload' => ["\"{$httpd}\" -k restart -n \"{$serviceName}\"", 'Apache reload'],
                'status' => ["sc query \"{$serviceName}\"", 'Apache status'],
                'renew_ssl' => ['certbot renew', 'SSL renew'],
                default => ['', 'Unsupported action'],
            };
        }

        return match ($action) {
            'test' => ['apache2ctl -t', 'Apache config test'],
            'start' => ['systemctl start apache2', 'Apache start'],
            'stop' => ['systemctl stop apache2', 'Apache stop'],
            'restart' => ['systemctl restart apache2', 'Apache restart'],
            'reload' => ['apache2ctl -t && systemctl reload apache2', 'Apache reload'],
            'status' => ['systemctl status apache2 --no-pager', 'Apache status'],
            'renew_ssl' => ['certbot renew', 'SSL renew'],
            default => ['', 'Unsupported action'],
        };
    }

    /**
     * @param array<string, mixed> $apache
     */
    private function detectServiceStatus(array $apache): string
    {
        if ((string) ($apache['os_family'] ?? '') === 'Windows') {
            $serviceName = (string) ($apache['service_name'] ?? 'wampapache64');
            $result = Process::timeout(20)->run("sc query \"{$serviceName}\"");
            $output = strtoupper($result->output().' '.$result->errorOutput());
            if (str_contains($output, 'RUNNING')) {
                return 'running';
            }
            if (str_contains($output, 'STOPPED')) {
                return 'stopped';
            }

            return 'unknown';
        }

        $result = Process::timeout(20)->run('systemctl is-active apache2');
        $status = trim($result->output());

        return $status !== '' ? $status : 'unknown';
    }

    /**
     * @param array<string, mixed> $nginx
     */
    private function detectNginxServiceStatus(array $nginx): string
    {
        if ((string) ($nginx['os_family'] ?? '') === 'Windows') {
            $serviceName = (string) ($nginx['service_name'] ?? 'wampnginx64');
            $result = Process::timeout(20)->run("sc query \"{$serviceName}\"");
            $output = strtoupper($result->output().' '.$result->errorOutput());
            if (str_contains($output, 'RUNNING')) {
                return 'running';
            }
            if (str_contains($output, 'STOPPED')) {
                return 'stopped';
            }

            return 'unknown';
        }

        $result = Process::timeout(20)->run('systemctl is-active nginx');
        $status = trim($result->output());

        return $status !== '' ? $status : 'unknown';
    }

    /**
     * @return array<string, mixed>
     */
    private function apacheRuntimeInfo(): array
    {
        $os = strtoupper(PHP_OS_FAMILY);

        if ($os === 'WINDOWS') {
            $httpd = trim((string) env('APACHE_HTTPD_PATH', ''));
            if ($httpd === '') {
                $matches = glob('D:/wamp64/bin/apache/apache*/bin/httpd.exe');
                $httpd = is_array($matches) && count($matches) > 0 ? (string) end($matches) : '';
            }

            $mainConf = trim((string) env('APACHE_MAIN_CONF_PATH', ''));
            if ($mainConf === '' && $httpd !== '') {
                $mainConf = dirname(dirname($httpd)).DIRECTORY_SEPARATOR.'conf'.DIRECTORY_SEPARATOR.'httpd.conf';
            }

            $sharedVhost = trim((string) env('APACHE_SHARED_VHOST_FILE', ''));
            if ($sharedVhost === '' && $mainConf !== '') {
                $sharedVhost = dirname($mainConf).DIRECTORY_SEPARATOR.'extra'.DIRECTORY_SEPARATOR.'httpd-vhosts-serverpanel.conf';
            }

            return [
                'os_family' => 'Windows',
                'httpd_path' => $httpd,
                'service_name' => trim((string) env('APACHE_SERVICE_NAME', 'wampapache64')),
                'main_conf' => $mainConf,
                'shared_vhost_file' => $sharedVhost,
                'include_hint' => 'Include conf/extra/httpd-vhosts-serverpanel.conf in httpd.conf if not already included.',
            ];
        }

        return [
            'os_family' => 'Linux',
            'httpd_path' => '/usr/sbin/apache2',
            'service_name' => 'apache2',
            'main_conf' => '/etc/apache2/apache2.conf',
            'shared_vhost_file' => trim((string) env('APACHE_SHARED_VHOST_FILE', '/etc/apache2/sites-available/serverpanel-shared.conf')),
            'include_hint' => 'Enable site: ln -s sites-available/serverpanel-shared.conf sites-enabled/serverpanel-shared.conf and reload apache.',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function nginxRuntimeInfo(): array
    {
        $os = strtoupper(PHP_OS_FAMILY);

        if ($os === 'WINDOWS') {
            $binaryPath = trim((string) env('NGINX_BINARY_PATH', ''));
            if ($binaryPath === '') {
                $matches = glob('D:/wamp64/bin/nginx/nginx*/nginx.exe');
                $binaryPath = is_array($matches) && count($matches) > 0 ? (string) end($matches) : '';
            }

            $mainConf = trim((string) env('NGINX_MAIN_CONF_PATH', ''));
            if ($mainConf === '' && $binaryPath !== '') {
                $mainConf = dirname($binaryPath).DIRECTORY_SEPARATOR.'conf'.DIRECTORY_SEPARATOR.'nginx.conf';
            }

            return [
                'os_family' => 'Windows',
                'binary_path' => $binaryPath,
                'service_name' => trim((string) env('NGINX_SERVICE_NAME', 'wampnginx64')),
                'main_conf' => $mainConf,
                'sites_available_path' => '',
                'sites_enabled_path' => '',
                'include_hint' => 'Use include directives in nginx.conf/server blocks for generated site files.',
            ];
        }

        return [
            'os_family' => 'Linux',
            'binary_path' => '/usr/sbin/nginx',
            'service_name' => 'nginx',
            'main_conf' => '/etc/nginx/nginx.conf',
            'sites_available_path' => '/etc/nginx/sites-available',
            'sites_enabled_path' => '/etc/nginx/sites-enabled',
            'include_hint' => 'Enable Nginx sites by linking sites-available to sites-enabled, then run nginx -t and reload.',
        ];
    }

    private function defaultRootPathForDomain(string $domain): string
    {
        $base = trim((string) config('app.server_base_dir', ''));
        if ($base === '') {
            $base = strtoupper(PHP_OS_FAMILY) === 'WINDOWS' ? dirname(base_path()) : '/home';
        }

        $owner = preg_replace('/[^a-z0-9]+/i', '_', $domain) ?: 'website';
        $owner = trim((string) $owner, '_');
        if ($owner === '') {
            $owner = 'website';
        }

        return rtrim($base, "\\/").DIRECTORY_SEPARATOR.$owner.DIRECTORY_SEPARATOR.'public_html';
    }

    private function renderVhostBlock(string $domain, string $rootPath): string
    {
        $safeRoot = str_replace('\\', '/', trim($rootPath));
        $logDomain = preg_replace('/[^a-z0-9\.\-_]+/i', '-', $domain) ?: 'site';

        return <<<CONF
<VirtualHost *:80>
    ServerName {$domain}
    ServerAlias www.{$domain}
    DocumentRoot "{$safeRoot}"

    <Directory "{$safeRoot}">
        AllowOverride All
        Options FollowSymLinks
        Require all granted

        <IfModule mod_dir.c>
            FallbackResource /index.php
        </IfModule>
    </Directory>

    DirectoryIndex index.php index.html index.htm

    ErrorLog "\${APACHE_LOG_DIR}/{$logDomain}-error.log"
    CustomLog "\${APACHE_LOG_DIR}/{$logDomain}-access.log" combined
</VirtualHost>
CONF;
    }

    /**
     * @param array<string, mixed>|null $website
     * @param array<string, mixed> $apache
     * @param array<string, mixed> $nginx
     * @return array<string, mixed>
     */
    private function buildWebsiteVhostPreview(?array $website, array $apache, array $nginx): array
    {
        if (! is_array($website)) {
            return $this->emptyVhostPreview('no website selected');
        }

        $domain = $this->normalizeDomain((string) ($website['domain'] ?? ''));
        $rootPath = trim(str_replace('\\', '/', (string) ($website['root_path'] ?? '')));
        $phpVersion = $this->normalizePhpVersionForSocket((string) ($website['php_version'] ?? '8.3'));

        if ($domain === '' || $rootPath === '') {
            return $this->emptyVhostPreview('missing website data');
        }

        $apachePath = $this->existingApacheVhostPath($domain, $apache);
        $nginxPath = $this->existingNginxVhostPath($domain, $nginx);
        $apacheExists = $apachePath !== '' && is_file($apachePath);
        $nginxExists = $nginxPath !== '' && is_file($nginxPath);

        $apacheContent = $apacheExists
            ? (string) @file_get_contents($apachePath)
            : $this->renderApacheVhostPreviewTemplate($domain, $rootPath, $phpVersion);
        $nginxContent = $nginxExists
            ? (string) @file_get_contents($nginxPath)
            : $this->renderNginxVhostPreviewTemplate($domain, $rootPath);

        return [
            'apache' => [
                'path' => $apachePath,
                'exists' => $apacheExists,
                'source' => $apacheExists ? 'loaded from file' : 'rendered template preview',
                'content' => $apacheContent,
            ],
            'nginx' => [
                'path' => $nginxPath,
                'exists' => $nginxExists,
                'source' => $nginxExists ? 'loaded from file' : 'rendered template preview',
                'content' => $nginxContent,
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function emptyVhostPreview(string $reason): array
    {
        return [
            'apache' => [
                'path' => '',
                'exists' => false,
                'source' => $reason,
                'content' => '',
            ],
            'nginx' => [
                'path' => '',
                'exists' => false,
                'source' => $reason,
                'content' => '',
            ],
        ];
    }

    /**
     * @param array<string, mixed> $apache
     * @return array<int, string>
     */
    private function apacheVhostPaths(string $domain, array $apache): array
    {
        if (strtolower((string) ($apache['os_family'] ?? '')) === 'windows') {
            $sharedPath = trim((string) ($apache['shared_vhost_file'] ?? ''));

            return $sharedPath !== '' ? [$sharedPath] : [];
        }

        $domain = $this->normalizeDomain($domain);
        if ($domain === '') {
            return [];
        }

        $primaryPath = '/etc/apache2/sites-available/'.$this->vhostFileBaseName($domain).'.conf';
        $legacyPath = '/etc/apache2/sites-available/'.$domain.'.conf';

        if ($legacyPath === $primaryPath) {
            return [$primaryPath];
        }

        return [$primaryPath, $legacyPath];
    }

    /**
     * @param array<string, mixed> $nginx
     * @return array<int, string>
     */
    private function nginxVhostPaths(string $domain, array $nginx): array
    {
        if (strtolower((string) ($nginx['os_family'] ?? '')) === 'windows') {
            $mainConf = trim((string) ($nginx['main_conf'] ?? ''));

            return $mainConf !== '' ? [$mainConf] : [];
        }

        $domain = $this->normalizeDomain($domain);
        if ($domain === '') {
            return [];
        }

        $primaryPath = '/etc/nginx/sites-available/'.$this->vhostFileBaseName($domain).'.conf';
        $legacyPath = '/etc/nginx/sites-available/'.$domain.'.conf';

        if ($legacyPath === $primaryPath) {
            return [$primaryPath];
        }

        return [$primaryPath, $legacyPath];
    }

    /**
     * @param array<string, mixed> $apache
     */
    private function existingApacheVhostPath(string $domain, array $apache): string
    {
        $paths = $this->apacheVhostPaths($domain, $apache);
        foreach ($paths as $path) {
            if (is_file($path)) {
                return $path;
            }
        }

        return $paths[0] ?? '';
    }

    /**
     * @param array<string, mixed> $nginx
     */
    private function existingNginxVhostPath(string $domain, array $nginx): string
    {
        $paths = $this->nginxVhostPaths($domain, $nginx);
        foreach ($paths as $path) {
            if (is_file($path)) {
                return $path;
            }
        }

        return $paths[0] ?? '';
    }

    private function renderApacheVhostPreviewTemplate(string $domain, string $rootPath, string $phpVersion): string
    {
        $domain = $this->normalizeDomain($domain);
        $rootPath = trim(str_replace('\\', '/', $rootPath));
        $phpVersion = $this->normalizePhpVersionForSocket($phpVersion);
        $backendPort = $this->apacheBackendPort();
        $serverAlias = $this->shouldAddWwwAlias($domain) ? "\n    ServerAlias www.{$domain}" : '';
        $socketPath = "/run/php/php{$phpVersion}-fpm.sock";
        $logName = $this->vhostLogBaseName($domain);

        return <<<CONF
<VirtualHost *:{$backendPort}>
    ServerName {$domain}{$serverAlias}
    DocumentRoot {$rootPath}

    <Directory {$rootPath}>
        AllowOverride All
        Options FollowSymLinks
        Require all granted

        <IfModule mod_dir.c>
            FallbackResource /index.php
        </IfModule>
    </Directory>

    DirectoryIndex index.php index.html index.htm

    <FilesMatch \\.php$>
        SetHandler "proxy:unix:{$socketPath}|fcgi://localhost/"
    </FilesMatch>

    ErrorLog \${APACHE_LOG_DIR}/{$logName}_error.log
    CustomLog \${APACHE_LOG_DIR}/{$logName}_access.log combined
</VirtualHost>
CONF;
    }

    private function renderNginxVhostPreviewTemplate(string $domain, string $rootPath): string
    {
        $domain = $this->normalizeDomain($domain);
        $rootPath = trim(str_replace('\\', '/', $rootPath));
        if ($rootPath === '') {
            $rootPath = '/var/www/html';
        }

        $listenPort = $this->nginxPrimaryPort();
        $backendPort = $this->apacheBackendPort();
        $logName = $this->vhostLogBaseName($domain);
        $serverAlias = $this->shouldAddWwwAlias($domain) ? " www.{$domain}" : '';

        return <<<CONF
server {
    listen {$listenPort};
    listen [::]:{$listenPort};
    server_name {$domain}{$serverAlias};
    root {$rootPath};
    index index.php index.html index.htm;

    access_log /var/log/nginx/{$logName}_access.log;
    error_log /var/log/nginx/{$logName}_error.log;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        try_files \$uri @apache;
    }

    location ~ /\\. {
        deny all;
    }

    location ~* \\.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp|avif|woff2?)$ {
        expires 30d;
        access_log off;
        try_files \$uri @apache;
    }

    location ~ \\.php(?:\$|/) {
        proxy_pass http://127.0.0.1:{$backendPort};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 30s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }

    location / {
        proxy_pass http://127.0.0.1:{$backendPort};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 30s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }

    location @apache {
        proxy_pass http://127.0.0.1:{$backendPort};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 30s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
CONF;
    }

    private function apacheBackendPort(): int
    {
        return $this->normalizePort(config('app.apache_backend_port'), self::DEFAULT_APACHE_BACKEND_PORT);
    }

    private function nginxPrimaryPort(): int
    {
        return $this->normalizePort(config('app.nginx_primary_port'), self::DEFAULT_NGINX_PRIMARY_PORT);
    }

    private function normalizePort(mixed $value, int $fallback): int
    {
        if (is_string($value)) {
            $value = trim($value);
        }

        if ((is_string($value) || is_int($value)) && preg_match('/^\d+$/', (string) $value) === 1) {
            $port = (int) $value;
            if ($port >= 1 && $port <= 65535) {
                return $port;
            }
        }

        return $fallback;
    }

    private function normalizeDomain(string $domain): string
    {
        return strtolower(trim($domain));
    }

    private function normalizePhpVersionForSocket(string $phpVersion): string
    {
        $normalized = trim($phpVersion);
        if (preg_match('/^\d+\.\d+$/', $normalized) !== 1) {
            return '8.3';
        }

        return $normalized;
    }

    private function vhostTokenFromDomain(string $domain): string
    {
        $normalizedDomain = $this->normalizeDomain($domain);
        $token = strtolower((string) preg_replace('/[^a-z0-9.-]+/', '-', $normalizedDomain));
        $token = trim($token, '-');

        return $token !== '' ? $token : 'site';
    }

    private function vhostFileBaseName(string $domain): string
    {
        $normalizedDomain = $this->normalizeDomain($domain);
        $token = $this->vhostTokenFromDomain($normalizedDomain);
        $hash = substr(sha1($normalizedDomain), 0, 12);
        if (strlen($token) > 110) {
            $token = substr($token, 0, 110);
        }

        return $token.'-'.$hash;
    }

    private function vhostLogBaseName(string $domain): string
    {
        $normalizedDomain = $this->normalizeDomain($domain);
        $token = $this->vhostTokenFromDomain($normalizedDomain);
        $hash = substr(sha1($normalizedDomain), 0, 12);
        if (strlen($token) > 52) {
            $token = substr($token, 0, 52);
        }

        return $token.'-'.$hash;
    }

    private function shouldAddWwwAlias(string $domain): bool
    {
        $labels = array_values(array_filter(explode('.', $this->normalizeDomain($domain))));
        if (count($labels) < 2) {
            return false;
        }

        [, $subLabels] = $this->splitDomainParts($labels);
        if (count($subLabels) === 0) {
            return true;
        }

        return count($subLabels) === 1 && $subLabels[0] === 'www';
    }

    /**
     * @param array<int, string> $labels
     * @return array{0: array<int, string>, 1: array<int, string>}
     */
    private function splitDomainParts(array $labels): array
    {
        $count = count($labels);
        if ($count < 2) {
            return [$labels, []];
        }

        $suffixParts = 1;
        if ($count >= 3) {
            $lastTwo = strtolower($labels[$count - 2].'.'.$labels[$count - 1]);
            if (in_array($lastTwo, (array) config('serverpanel.compound_public_suffixes', []), true)) {
                $suffixParts = 2;
            }
        }

        $registrableLength = $suffixParts + 1;
        if ($count < $registrableLength) {
            $registrableLength = 2;
        }

        $registrableLabels = array_slice($labels, -$registrableLength);
        $subLabels = array_slice($labels, 0, -$registrableLength);

        return [$registrableLabels, $subLabels];
    }
}
