<?php
/**
 * ServerPanel Roundcube Configuration Template
 * Installer updates DB credentials and runtime values after copy.
 */


declare(strict_types=1);

$config = [];

// Database Connection
$config['db_dsnw'] = 'mysql://roundcube:STRONG_PASSWORD@127.0.0.1/roundcube';

// System Paths
$config['temp_dir'] = '/var/lib/roundcube/temp';
$config['log_dir'] = '/var/log/roundcube';

// IMAP Settings (Inbound)
// Use tls:// for encryption over port 143
$config['default_host'] = 'tls://127.0.0.1';
$config['default_port'] = 143;

// SMTP Settings (Outbound)
$config['smtp_server'] = 'tls://127.0.0.1';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

// Security & Sessions
$config['des_key'] = ''; // SHOULD BE GENERATED BY INSTALLER
$config['session_lifetime'] = 30; // Minutes; shorter is generally safer
$config['auto_create_user'] = true;
$config['login_autocomplete'] = 2;

// Skin and UI
$config['skin'] = 'elastic'; // The modern, responsive Roundcube skin
