<script setup>
import { computed, ref } from 'vue';
import { usePage } from '@inertiajs/vue3';
const props=defineProps({website:{type:Object,required:true},compact:{type:Boolean,default:false}});
const page=usePage();const command=ref('');const output=ref('Sandbox ready. Commands run only inside /workspace.\n');const running=ref(false);
const panelToken=computed(()=>String(page.props.panel?.token||''));
const panelRoute=(name,params={})=>panelToken.value?route(name,{token:panelToken.value,...params}):route(name,params);
const csrf=()=>document.querySelector('meta[name="csrf-token"]')?.content||'';
const run=async()=>{const value=command.value.trim();if(!value||running.value)return;output.value+=`\n$ ${value}\n`;command.value='';running.value=true;try{const response=await fetch(panelRoute('websites.terminal.execute',{id:props.website.id}),{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf()},body:JSON.stringify({command:value})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Command failed.');output.value+=(data.output||'(no output)')+`\n[exit ${data.exit_code}]\n`;}catch(error){output.value+=`Blocked/Error: ${error.message}\n`;}finally{running.value=false;}};
</script>
<template><div class="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 shadow-sm"><div class="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div><p class="text-sm font-semibold text-slate-100">Sandbox Terminal</p><p class="text-[11px] text-emerald-400">{{ website.site_owner }} · /workspace · network isolated</p></div><button type="button" class="text-xs text-slate-400 hover:text-white" @click="output='Sandbox ready. Commands run only inside /workspace.\n'">Clear</button></div><pre :class="['overflow-auto whitespace-pre-wrap break-words p-4 font-mono text-xs leading-5 text-slate-200',compact?'h-44':'h-[55vh]']">{{ output }}</pre><form class="flex border-t border-slate-800" @submit.prevent="run"><span class="px-3 py-3 font-mono text-sm text-emerald-400">$</span><input v-model="command" :disabled="running" autocomplete="off" spellcheck="false" class="min-w-0 flex-1 border-0 bg-transparent px-1 py-3 font-mono text-sm text-white outline-none ring-0 placeholder:text-slate-600 focus:ring-0" placeholder="pwd, ls, php artisan..."/><button :disabled="running||!command.trim()" class="m-1.5 rounded-lg bg-emerald-600 px-4 text-xs font-semibold text-white disabled:opacity-40">{{ running?'Running...':'Run' }}</button></form></div></template>
